### ISSUE TITLE
Sample JSON data for the local database

### ISSUE THREAD

**Issue by mauriciabad** [ItsBurpee/EverdeckLibrary#1]
Hi there! First of all, thank you for this awesome project! 🙌

I'm currently setting it up on my local machine to explore contributing—particularly with some CSS style improvements. However, I'm struggling with the database setup.

I’ve successfully created a MongoDB database, but it's currently empty. Would it be possible to provide some sample JSON data that could be easily imported into a local database? Perhaps it could be placed in a `/docs/db` folder for future users.

Also, it would be helpful if the documentation specified that the database name should be `everdeck_database`.

> A little about me: I built the DIY Multideck along with its [game mappings website](https://diymultideck.mauri.app/games/) ([source code](https://github.com/mauriciabad/diy-multideck-website)), which is quite similar to your project. Because of this, I already have some context and would love to help with small tasks, share feedback, or just chat about any questions you might have. 😊 We can talk on Signal, WhatsApp, or whatever you prefer (we can exchange numbers via email).

**Comment by NathanCruz98** [comment]
Hello! Thanks for compliment and I believe I do remember seeing your post of the DIY Multideck on BGG.

I've now provided some sample JSONs for 3 of the first few games we made entries for when we were developing the project. I've also adjusted the documentation to bring attention to these examples alongside explaining the database name.

Hope this helps with your potential contributions!
